Add #include <algorithm> to support std::min
std::min is defined in the <algorithm> header. It's not advised to rely on <iostream> to include it for you.
The repository as it is gives a compilation error on Windows: "libb64/include/b64/encode.h(89): error C3861: 'min': identifier not found".